from enum import Enum, IntEnum


class OS(Enum):
    LINUX = "linux"
    ANDROID = "android"
    IOS = "ios"
    WINDOWS = "windows"
    MAC = "mac"


class MODE(Enum):
    SPAWN = "spawn"
    ATTACH = "attach"
    ENUM = "enum"


class ARCHITECTURE(Enum):
    IA32 = "ia32"
    X64 = "x64"
    ARM = "arm"
    ARM64 = "arm64"


class WinDef(IntEnum):
    PROCESS_ALL_ACCESS = 0x1F0FFF

    TH32CS_SNAPPROCESS = 0x2
    TH32CS_SNAPTHREAD = 0x4
    TH32CS_SNAPMODULE = 0x8

    PAGE_NOACCESS = 1
    PAGE_READONLY = 2
    PAGE_READWRITE = 4
    PAGE_WRITECOPY = 8
    PAGE_EXECUTE = 16
    PAGE_EXECUTE_READ = 32
    PAGE_EXECUTE_READWRITE = 64

    MEM_MAPPED = 262144
    MEM_PRIVATE = 131072

    PROT_READ = 1
    PROT_WRITE = 2
    PROT_EXEC = 4

    MAP_SHARED = 1
    MAP_PRIVATE = 2
    MAP_ANONYMOUS = 32

    VQE_PAGEDONLY = 1
    VQE_DIRTYONLY = 2
    VQE_NOSHARED = 4


class CECMD(IntEnum):
    CMD_GETVERSION = 0
    CMD_CLOSECONNECTION = 1
    CMD_TERMINATESERVER = 2
    CMD_OPENPROCESS = 3
    CMD_CREATETOOLHELP32SNAPSHOT = 4
    CMD_PROCESS32FIRST = 5
    CMD_PROCESS32NEXT = 6
    CMD_CLOSEHANDLE = 7
    CMD_VIRTUALQUERYEX = 8
    CMD_READPROCESSMEMORY = 9
    CMD_WRITEPROCESSMEMORY = 10
    CMD_STARTDEBUG = 11
    CMD_STOPDEBUG = 12
    CMD_WAITFORDEBUGEVENT = 13
    CMD_CONTINUEFROMDEBUGEVENT = 14
    CMD_SETBREAKPOINT = 15
    CMD_REMOVEBREAKPOINT = 16
    CMD_SUSPENDTHREAD = 17
    CMD_RESUMETHREAD = 18
    CMD_GETTHREADCONTEXT = 19
    CMD_SETTHREADCONTEXT = 20
    CMD_GETARCHITECTURE = 21
    CMD_MODULE32FIRST = 22
    CMD_MODULE32NEXT = 23
    CMD_GETSYMBOLLISTFROMFILE = 24
    CMD_LOADEXTENSION = 25
    CMD_ALLOC = 26
    CMD_FREE = 27
    CMD_CREATETHREAD = 28
    CMD_LOADMODULE = 29
    CMD_SPEEDHACK_SETSPEED = 30
    CMD_VIRTUALQUERYEXFULL = 31
    CMD_GETREGIONINFO = 32
    CMD_GETABI = 33
    CMD_SET_CONNECTION_NAME = 34
    CMD_CREATETOOLHELP32SNAPSHOTEX = 35
    CMD_CHANGEMEMORYPROTECTION = 36
    CMD_GETOPTIONS = 37
    CMD_GETOPTIONVALUE = 38
    CMD_SETOPTIONVALUE = 39
    CMD_PTRACE_MMAP = 40
    CMD_OPENNAMEDPIPE = 41
    CMD_PIPEREAD = 42
    CMD_PIPEWRITE = 43
    CMD_GETCESERVERPATH = 44
    CMD_ISANDROID = 45
    CMD_AOBSCAN = 200
    CMD_COMMANDLIST2 = 255


class JAVAPIPECMD(IntEnum):
    JAVACMD_STARTCODECALLBACKS = 0
    JAVACMD_STOPCODECALLBACKS = 1
    JAVACMD_GETLOADEDCLASSES = 2
    JAVACMD_DEREFERENCELOCALOBJECT = 3
    JAVACMD_GETCLASSMETHODS = 4
    JAVACMD_GETCLASSFIELDS = 5
    JAVACMD_GETIMPLEMENTEDINTERFACES = 6
    JAVAVMD_FINDREFERENCESTOOBJECT = 7
    JAVACMD_FINDJOBJECT = 8
    JAVACMD_GETCLASSSIGNATURE = 9
    JAVACMD_GETSUPERCLASS = 10
    JAVACMD_GETOBJECTCLASS = 11
    JAVACMD_GETCLASSDATA = 12
    JAVACMD_REDEFINECLASS = 13
    JAVACMD_FINDCLASS = 14
    JAVACMD_GETCAPABILITIES = 15
    JAVACMD_GETMETHODNAME = 16
    JAVACMD_INVOKEMETHOD = 17
    JAVACMD_FINDCLASSOBJECTS = 18
    JAVACMD_ADDTOBOOTSTRAPCLASSLOADERPATH = 19
    JAVACMD_ADDTOSYSTEMCLASSLOADERPATH = 20
    JAVACMD_PUSHLOCALFRAME = 21
    JAVACMD_POPLOCALFRAME = 22
    JAVACMD_GETFIELDDECLARINGCLASS = 23
    JAVACMD_GETFIELDSIGNATURE = 24
    JAVACMD_GETFIELD = 25
    JAVACMD_SETFIELD = 26
    JAVACMD_STARTSCAN = 27
    JAVACMD_REFINESCANRESULTS = 28
    JAVACMD_GETSCANRESULTS = 29
    JAVACMD_FINDWHATWRITES = 30
    JAVACMD_STOPFINDWHATWRITES = 31
    JAVACMD_GETMETHODDECLARINGCLASS = 32


class MONOPIPECMD(IntEnum):
    MONOCMD_INITMONO = 0
    MONOCMD_OBJECT_GETCLASS = 1
    MONOCMD_ENUMDOMAINS = 2
    MONOCMD_SETCURRENTDOMAIN = 3
    MONOCMD_ENUMASSEMBLIES = 4
    MONOCMD_GETIMAGEFROMASSEMBLY = 5
    MONOCMD_GETIMAGENAME = 6
    MONOCMD_ENUMCLASSESINIMAGE = 7
    MONOCMD_ENUMFIELDSINCLASS = 8
    MONOCMD_ENUMMETHODSINCLASS = 9
    MONOCMD_COMPILEMETHOD = 10

    MONOCMD_GETMETHODHEADER = 11
    MONOCMD_GETMETHODHEADER_CODE = 12
    MONOCMD_LOOKUPRVA = 13
    MONOCMD_GETJITINFO = 14
    MONOCMD_FINDCLASS = 15
    MONOCMD_FINDMETHOD = 16
    MONOCMD_GETMETHODNAME = 17
    MONOCMD_GETMETHODCLASS = 18
    MONOCMD_GETCLASSNAME = 19
    MONOCMD_GETCLASSNAMESPACE = 20
    MONOCMD_FREEMETHOD = 21
    MONOCMD_TERMINATE = 22
    MONOCMD_DISASSEMBLE = 23
    MONOCMD_GETMETHODSIGNATURE = 24
    MONOCMD_GETPARENTCLASS = 25
    MONOCMD_GETSTATICFIELDADDRESSFROMCLASS = 26
    MONOCMD_GETFIELDCLASS = 27
    MONOCMD_GETARRAYELEMENTCLASS = 28
    MONOCMD_FINDMETHODBYDESC = 29
    MONOCMD_INVOKEMETHOD = 30
    MONOCMD_LOADASSEMBLY = 31
    MONOCMD_GETFULLTYPENAME = 32
    MONOCMD_OBJECT_NEW = 33
    MONOCMD_OBJECT_INIT = 34
    MONOCMD_GETVTABLEFROMCLASS = 35
    MONOCMD_GETMETHODPARAMETERS = 36
    MONOCMD_ISCLASSGENERIC = 37
    MONOCMD_ISIL2CPP = 38
    MONOCMD_FILLOPTIONALFUNCTIONLIST = 39
    MONOCMD_GETSTATICFIELDVALUE = 40
    MONOCMD_SETSTATICFIELDVALUE = 41
    MONOCMD_GETCLASSIMAGE = 42
    MONOCMD_FREE = 43
    MONOCMD_GETIMAGEFILENAME = 44
    MONOCMD_GETCLASSNESTINGTYPE = 45
    MONOCMD_LIMITEDCONNECTION = 46
    MONOCMD_GETMONODATACOLLECTORVERSION = 47
    MONOCMD_NEWSTRING = 48
    MONOCMD_ENUMIMAGES = 49
    MONOCMD_ENUMCLASSESINIMAGEEX = 50
    MONOCMD_ISCLASSENUM = 51
    MONOCMD_ISCLASSVALUETYPE = 52
    MONOCMD_ISCLASSISSUBCLASSOF = 53
    MONOCMD_ARRAYELEMENTSIZE = 54
    MONOCMD_GETCLASSTYPE = 55
    MONOCMD_GETCLASSOFTYPE = 56
    MONOCMD_GETTYPEOFMONOTYPE = 57
    MONOCMD_GETREFLECTIONTYPEOFCLASSTYPE = 58
    MONOCMD_GETREFLECTIONMETHODOFMONOMETHOD = 59
    MONOCMD_MONOOBJECTUNBOX = 60
    MONOCMD_MONOARRAYNEW = 61
    MONOCMD_ENUMINTERFACESOFCLASS = 62
